###Numpy 기본 사용법

In [ ]:
import numpy as np

array = np.array([1,2,3])
print(array.size)#배열의 크기
print(array.dtype)#배열 원소 타입
print(array[2]) # 배열 인덱스 2의 원소

3
int64
3


In [ ]:
import numpy as np 

#0부터 3까지의 배열 만들기
array1 = np.arange(4)
print(array1)

#0으로 초기화
array2 = np.zeros((4,4), dtype=float)
print(array2)

#1로 초기화 

array3 = np.ones((3,3) ,dtype=str)
print(array3)

#빈칸이 나오는 이유는? 
array4 = np.zeros((3,3), dtype= str)
print(array4)

#0~9까지 랜덤하게 초기화된 배열 만들기
array5 = np.random.randint(0,10,(3,3))
print(array5)

#평균이 0이고 표준편차가 1인 표준 정규를 띄는 배열 
array6 = np.random.normal(0,1,(3,3))
print(array6)

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]
[['' '' '']
 ['' '' '']
 ['' '' '']]
[[7 0 6]
 [7 2 6]
 [3 0 2]]
[[ 0.6811572   0.03661005  0.35353832]
 [-1.38519269  1.02801126  0.0292836 ]
 [-1.45796497  1.10251558 -1.80761829]]


다양한 형태로 합치기

In [ ]:
import numpy as np

array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array3 = np.concatenate([array1, array2])

#.shape -> array에 대해서 몇행, 몇열 행렬로 구성되어있는지 알려줌
print(array3.shape)
print(array3)


(6,)
[1 2 3 4 5 6]


In [ ]:
import numpy as np

array1 = np.arange(4).reshape(1,4)
array2 = np.arange(8).reshape(2,4)
array3 = np.concatenate([array1, array2], axis = 0)

print(array3.shape)
print(array3)

(3, 4)
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


Numpy의 형태를 변경할 수도 있다

In [ ]:
import numpy as np

array1 = np.array([1,2,3,4])
array2 = array1.reshape((2,2))

print(array2.shape)
print(array2)

(2, 2)
[[1 2]
 [3 4]]




Numpy의 형태를 나누기 



In [ ]:
import numpy as np

array = np.arange(8).reshape(2,4)
left, right = np.split(array, [2], axis = 1)

print(array)
print(left.shape)
print(left)
print(right.shape)
print(right)
print(right[1][1])

[[0 1 2 3]
 [4 5 6 7]]
(2, 2)
[[0 1]
 [4 5]]
(2, 2)
[[2 3]
 [6 7]]
7


In [ ]:
import numpy as np

array = np.arange(12).reshape(2,6)
left, right = np.split(array, [3], axis = 1)

print(array)
print(left.shape)
print(left)
print(right.shape)
print(right)
print(right[1][1])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 3)
[[0 1 2]
 [6 7 8]]
(2, 3)
[[ 3  4  5]
 [ 9 10 11]]
10
